// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    FullScreen: typeof import('./src/components/full-screen/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZBorder: typeof import('./src/components/z-border/index.vue')['default']
    ZCard: typeof import('./src/components/z-card/index.vue')['default']
    ZCardData: typeof import('./src/components/z-card-data/index.vue')['default']
    ZSort: typeof import('./src/components/z-sort/index.vue')['default']
  }
}
